use std::process::Command;

pub fn genKeys(){
    let mut run_ssh=Command::new("bash");
    run_ssh.arg("-c")
    .arg("ssh-keygen -q -t ed25519  -C 'generated by rust' -N '' -f ~/.ssh/id_ed25519");
    // .arg("-C 'example@example.com'") 
    // .arg("-N ''")
    // .arg("-f ~/.ssh/id_ed25519");
    // // let hello_1 = run_ssh.output().expect("failed to execute process");
    // let mut test_ls=Command::new("ls");
    // test_ls.arg("-l");
    let test_op=run_ssh.status().expect("Failed to run the process");
    // println!("status: {}", check.status());
    // println!("stdout: {}", String::from_utf8_lossy(&check.stdout));
    // println!("stderr: {}", String::from_utf8_lossy(&check.stderr));
    // if check.status == 0
    // {

    // }
            
    
}